version: "3"
services:
  go-agent-1:
    image: 'gocd/gocd-agent-alpine-3.16:v22.3.0'
    restart: unless-stopped
    container_name: gocd_agent_1
    environment:
      AGENT_AUTO_REGISTER_KEY: 'your_agent_autoregister_key'
      GO_SERVER_URL: https://your_ip_address:8154/go
    # For access to target
    # mount target folder
    # with this agent
    # volumes:
      # - ./target_folder:/agent_folder:z
