version: "3"
services:
  go-agent-1:
    image: 'gocd/gocd-agent-alpine-3.16:v22.3.0'
    restart: unless-stopped
    container_name: gocd_agent_1
    environment:
      AGENT_AUTO_REGISTER_KEY: '0cccb5eb-611d-4fdc-ac9d-eb8db8f0f0ae'
      GO_SERVER_URL: https://194.61.0.136:8154/go
    # For access to target
    # mount target folder
    # with this agent
    # volumes:
      # - ./target_folder:/agent_folder:z
