version: "3"
services:
  go-agent-1:
    image: 'gocd/gocd-agent-alpine-3.16:v22.3.0'
    container_name: $GOCD_AGENT_NAME
    restart: unless-stopped
    environment:
      AGENT_AUTO_REGISTER_KEY: $AGENT_AUTO_REGISTER_KEY
      GO_SERVER_URL: $GOCD_SERVER_URL
    working_dir: /app
    volumes:
      - target_folder:/app:z

volumes:
  target_folder:
    driver_opts:
      o: bind
      type: none
      device: $TARGET_FOLDER_PATH